[build-system]
requires = ["setuptools==66.1.1"]
build-backend = "setuptools.build_meta"

[project]
name = "src"
version = "0.1.0"
description = "In-Context Learning for Language Modeling"
requires-python = ">=3.10"